#!/usr/bin/python3

# Copyright (c) 2018, 2019 Peter Palfrader
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from lxml import etree

def main():
    """Load a graph from stdin or a file."""
    import argparse
    import sys

    argparser = argparse.ArgumentParser(description='Load a graph from a .line file')
    argparser.add_argument('--schema', help='schema definition file (.xsd)', type=argparse.FileType('rt'), default='graphml.xsd')
    argparser.add_argument('inputfile', help='Inputfile (.graphml)', nargs='?', type=argparse.FileType('rt'), default=sys.stdin)
    args = argparser.parse_args()

    schema_root = etree.XML(args.schema.read())
    schema = etree.XMLSchema(schema_root)
    xmlparser = etree.XMLParser(schema = schema)

    root = etree.fromstring(args.inputfile.read(), xmlparser)

if __name__ == '__main__' and __package__ is None:
    main()
